### PR TITLE
fix: use ows4R's built-in thing for bbox

### LINKED ISSUE #55: axes reversed for the extent of human_activities?
I kept get an error that my bbox was out of of coverage extent even though the polygon I am trying to sample is well within the bounds of the data (checked with map viewer, data is available for the location).

here is my query code:  
#layers[i] is "emodnet__vesseldensity_all" however the problem is recurrent for all human_activities layers

assign(paste(layers[i]), 
+ emdn_get_coverage(Ewcs,
+                 coverage_id = layers[i],
+                 bbox = bbox.E))

Error in `check_cov_contains_bbox()`:
! `bbox` boundaries "xmin" and "xmax" lie outside coverage extent. No overlapping data to download.
Run `rlang::last_error()` to see where the error occurred.

bbox.E is on the same projection as the data (EPSG:3857) (I also tried querying on the WGS84 extent)

if I go to the database summary directly (https://ows.emodnet-humanactivities.eu/wcs?service=WCS&request=GetCapabilities&version=2.0) I find that the BBox for that coverage is:

<ows:LowerCorner>-9763441.130289372 1684718.7349552144</ows:LowerCorner>
<ows:UpperCorner>1.086845880678606E7 2.28223599215428E7</ows:UpperCorner>

yet if I query what the bbox is via EMODnetWCS, I get:

emdn_get_bbox(emdn_get_coverage_summaries(Ewcs,"emodnet__vesseldensity_all")[[1]])
    xmin     ymin     xmax     ymax 
 1684719 -9763441 22822360 10868459 

it looks like the axes have been swapped around (ymin is xmin and ymax is xmax)?

### PR DESCRIPTION
**Pull request by maelle**
Fix #55 

With this branch

``` r
devtools::load_all()
#> ℹ Loading emodnet.wcs
#> Loading ISO 19139 XML schemas...
#> 
#> Loading ISO 19115-3 XML schemas...
#> 
#> Loading ISO 19139 codelists...
Ewcs <- emdn_init_wcs_client("human_activities")
#> ✔ WCS client created succesfully
#> ℹ Service: <https://ows.emodnet-humanactivities.eu/wcs>
#> ℹ Service: "2.0.1"
emdn_get_bbox(emdn_get_coverage_summaries(Ewcs, "emodnet__vesseldensity_all")[[
  1
]])
#>     xmin     ymin     xmax     ymax 
#> -9763441  1684719 10868459 22822360
```

<sup>Created on 2025-08-20 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

So like

```
<ows:BoundingBox crs="http://www.opengis.net/def/crs/EPSG/0/3857">
<ows:LowerCorner>-9763441.130289372 1684718.7349552144</ows:LowerCorner>
<ows:UpperCorner>1.086845880678606E7 2.28223599215428E7</ows:UpperCorner>
</ows:BoundingBox>
```

@pepijn-devries I'd appreciate your feedback on this PR too when you get a chance. Thank you!

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -239,20 +239,7 @@ emdn_get_coverage_dim_coefs <- function(
...
-  sf::st_bbox(
-    c(
-      xmin = lower[2L],
-      xmax = upper[2L],
-      ymin = lower[1L],
-      ymax = upper[1L]
-    ),
-    crs = extr_bbox_crs(summary)
-  )
+  summary$getBoundingBox()$BoundingBox$getBBOX()
```
Comment (maelle) [inline R/utils.R:242]: Maybe at the time there was a small bug in ows4R?

**Comment by pepijn-devries** [comment]
Forgot to look at this branch. Will try to do this weekend...
