### PR TITLE
fix: nil values conversion

### LINKED ISSUE #121: nil_values_as_na = TRUE does not convert NaN nil values to NA
**Description:**

When a WCS coverage has `NaN` as its nil value (as reported in metadata), the `nil_values_as_na = TRUE` argument in `emdn_get_coverage()` fails to convert these values to `NA`. The function also emits a confusing error message before reporting success.

Discovered while working on https://github.com/EMODnet/emodnet-bio-r-geo-tutorials/issues/10.

**Reprex:**

```r
library(emodnet.wcs)
library(terra)

hab_wcs <- emdn_init_wcs_client(service = "seabed_habitats")
test_bbox <- c(xmin = 0, ymin = 55, xmax = 2, ymax = 57)

# The nil value is correctly identified as NaN
summary <- emdn_get_coverage_summaries(
  hab_wcs, 
  "emodnet_open_maplibrary__GB000050_EFH_Whiting_SpawningGrounds"
)[[1]]
emdn_get_band_nil_values(summary)
#> GRAY_INDEX 
#>        NaN

# Download with nil_values_as_na = TRUE
r <- emdn_get_coverage(
  wcs = hab_wcs,
  coverage_id = "emodnet_open_maplibrary__GB000050_EFH_Whiting_SpawningGrounds",
  bbox = test_bbox,
  nil_values_as_na = TRUE
)
#> ! Error in `NaN` Returning NA
#> ✔ nil values NaN converted to NA on all bands.

# But NaN values are still present
sum(is.nan(values(r)))
#> [1] 4
```

**Cause:**

In `conv_nil_to_na()`, the comparison uses `>=`:

```r
terra::values(cov_raster)[terra::values(cov_raster) >= uniq_nil_val] <- NA
```

This doesn't work for `NaN` because `NaN >= NaN` returns `NA`, not `TRUE`. The function reports success but the NaN values remain unchanged.

**Suggested fix:**

Add a special case for NaN nil values using `is.nan()`:
 
```r
if (is.nan(uniq_nil_val)) {
  terra::values(cov_raster)[is.nan(terra::values(cov_raster))] <- NA
  cli_alert_success("nil values {.val NaN} converted to {.field NA} on all bands.")
} else if (is.numeric(uniq_nil_val)) {
  terra::values(cov_raster)[terra::values(cov_raster) >= uniq_nil_val] <- NA
  cli_alert_success("nil values {.val {uniq_nil_val}} converted to {.field NA} on all bands.")
}
```

The same pattern would need to be applied in the per-band loop below.

### PR DESCRIPTION
**Pull request by maelle**
Fix #121 

@annakrystalli I tried to simplify, bad idea?

Do you know of use cases where there are more than 1 nil value?

### CODE REVIEW

File: R/coverage.R [hunk 1]
```diff
@@ -201,52 +201,49 @@ emdn_get_coverage <- function(
...
+    },
+    .init = cov_raster
+  )
+}
 
-  # If nil_values differ between bands, replace nil_values individually.
-  n_bands <- terra::nlyr(cov_raster)
-  nil_values <- rep(nil_values, times = n_bands / length(nil_values))
+conv_band_nil_value <- function(band, cov_raster, summary, rangesubset) {
+  nil_val <- emdn_get_band_nil_values(summary, band)[rangesubset]
```
Comment (maelle) [inline R/coverage.R]: why do we have to subset with the range subset? Shouldn't the nil value be the same for the whole layer?

Comment (annakrystalli) [reply R/coverage.R]: Hmmm not sure why I set it up like that originally but your instinct makes sense to me. Might be worth investigating

File: R/coverage.R [hunk 2]
```diff
@@ -201,52 +201,49 @@ emdn_get_coverage <- function(
...
-    } else {
-      cli::cli_warn(
-        "!" = "Cannot convert non numeric nil value {.val {nil_value}} to NA
-          on band {.val {band_name}}"
-      )
-    }
+  if (is.numeric(nil_val)) {
+    terra::values(cov_raster[[band_idx]])[
+      terra::values(cov_raster[[band_idx]]) >= nil_val
+    ] <- NA
```
Comment (annakrystalli) [inline R/coverage.R]: I don't think this is right. Are you converting anything above or equal to the nil value to `NA`? what if the nil value is negative? (pretty sure I've seen something like -99999

File: tests/testthat/test-coverage.R [hunk 3]
```diff
@@ -90,3 +90,27 @@ test_that("emdn_get_coverage() works -- stack", {
...
+
+  # conversion
+  expect_snapshot(
+    r <- emdn_get_coverage(
+      wcs = hab_wcs,
+      coverage_id = coverage_id,
+      bbox = test_bbox,
+      nil_values_as_na = TRUE
+    )
+  )
```
Comment (annakrystalli) [inline tests/testthat/test-coverage.R]: Not sure this snapshot is really useful for testing this feature

File: R/coverage.R [hunk 4]
```diff
@@ -201,52 +201,49 @@ emdn_get_coverage <- function(
...
-    return(cov_raster)
-  }
+    },
+    .init = cov_raster
+  )
+}
 
-  # If nil_values differ between bands, replace nil_values individually.
-  n_bands <- terra::nlyr(cov_raster)
-  nil_values <- rep(nil_values, times = n_bands / length(nil_values))
```
[the remark this answers is not in the document]
Comment (maelle) [reply R/coverage.R]: @annakrystalli this above is partly why I refactored. I didn't understand the `rep()` call.

I'll work on this in the new year. If you have more use cases, I can add more test cases :smile_cat:

File: tests/testthat/test-coverage.R (hunk 3 above)
Comment (maelle) [reply tests/testthat/test-coverage.R]: I wanted to catch the verbosity.

File: R/coverage.R (hunk 4 above)
[the remark this answers is not in the document]
Comment (maelle) [reply R/coverage.R]: @annakrystalli this was the part I did not understand (line 228): how do we know each band got the correct nil value with that `rep()` call?

File: R/coverage.R [hunk 5]
```diff
@@ -189,64 +189,54 @@ emdn_get_coverage <- function(
...
+conv_band_nil_value <- function(band, cov_raster, summary) {
+  nil_val <- emdn_get_band_nil_values(summary, band)
 
-  for (band_idx in seq_len(n_bands)) {
-    nil_value <- nil_values[[band_idx]]
-    band_name <- names(nil_values)[band_idx]
+  band_idx <- which(emdn_get_band_descriptions(summary) == band)
```
Comment (maelle) [inline R/coverage.R]: this is actually not a great idea at all and won't work for stacks where you have more layers than bands. #125

File: R/coverage.R [hunk 6]
```diff
@@ -188,65 +188,53 @@ emdn_get_coverage <- function(
...
   cov_raster
 }
 
 # Convert coverage nil values to NA
-conv_nil_to_na <- function(cov_raster, summary, rangesubset) {
-  nil_values <- emdn_get_band_nil_values(summary)[rangesubset]
-  uniq_nil_val <- unique(nil_values)
+conv_nil_to_na <- function(cov_raster, nil_values) {
+  purrr::reduce(
+    names(nil_values),
```
Comment (maelle) [inline R/coverage.R]: note to self: use `kebabcase()` introduced in #126

File: R/coverage.R (hunk 5 above)
Comment (maelle) [reply R/coverage.R]: band whose names end with kebabcase of current nil value's name.

File: R/coverage.R [hunk 7]
```diff
@@ -188,65 +188,53 @@ emdn_get_coverage <- function(
...
-      cli_alert_success(
-        "nil values {.val {uniq_nil_val}} converted to {.field NA} on all bands."
-      )
-    } else {
-      cli::cli_warn(
-        "!" = "Cannot convert non numeric nil value {.val {uniq_nil_val}} to NA"
-      )
-    }
+  if (is.nan(nil_value)) {
+    terra::values(cov_raster[[band_idx]])[is.nan(terra::values(cov_raster[[
```
Comment (maelle) [inline R/coverage.R]: we might have several bands at once here, not sure terra::values would accept that, need to try.
